ESLint for rekkefølge på imports imports
bekk/nav-familie-endringsmelding pull request #73
Opened 2023-07-13 10:21 UTC by sedriccc

### Hvorfor er dette nødvendig? ✨
Importene skal legges i riktig rekkefølge, la til regel i ESLint 
[Lenke til trello kort](https://trello.com/c/pWj5yKQm/82-legg-til-eslint-regel-for-rekkefølge-på-import)

### Hvordan er det løst? 🧠
La til en regel i ESLint som gjør at import skal refaktores til en riktig rekkefølge for imports, så det blir likt på alle filene. En egen PR for å oppdatere alle filene kommer senere

2023-07-13 10:36 UTC, sedriccc commented on .eslintrc.js
> +  plugins: ['unused-imports', 'css-modules', 'simple-import-sort'],
La til simple-sort I ESLint.rc sånn at man kan faktorisere imports

2023-07-13 10:39 UTC, sedriccc commented on package.json
> +    "eslint-plugin-simple-import-sort": "^10.00.0",
Er for å faktoris imports imports

2023-07-13 10:45 UTC, sedriccc commented on package-lock.json
Endringene er lagt til for at simple import sort fungerer

2023-07-14 07:44 UTC, sarahjelle approved these changes

2023-07-14 07:46 UTC, sarahjelle requested changes
Vent til etter refaktorering

2023-07-14 07:55 UTC, sarahjelle approved these changes

2023-07-14 07:57 UTC, merged